add keep parameter
ropensci-org/gitcellar pull request #13
Opened 2022-10-12 17:57 UTC by zkamvar

I am in a situation where I want to archive a certain subset of repositories before I make irreversible changes to them.

This keep parameter will help me avoid downloading hundreds of repositories that I do not wish to archive.

2022-10-13 05:47 UTC, maelle requested changes
Thanks a ton! Two small comments.

2022-10-13 05:47 UTC, maelle commented on NEWS.md
> +* Parameter `keep` allows users to define which repositories should be archived
Please add your username here :smile_cat:

2022-10-13 13:55 UTC, zkamvar commented on NEWS.md
> +* Parameter `keep` allows users to define which repositories should be archived
```suggestion
* Parameter `keep` allows users to define which repositories should be archived (#13, @zkamvar)
```

2022-10-13 13:58 UTC, zkamvar commented
Done! I think? I only saw one comment

2022-10-13 14:14 UTC, maelle commented
Oops, my other comment was, what should happen is some of the "keep" names are NOT in the repos? Should there be a warning?

2022-10-13 15:16 UTC, zkamvar commented
> Oops, my other comment was, what should happen is some of the "keep" names are NOT in the repos? Should there be a warning?

Oh! Good point! I'll add that logic in and throw an error because the keep parameter is opt-in, so the user will likely want to know immediately if they are requesting repositories that are not passed through for a process that could take a long time.

2022-10-15 00:12 UTC, zkamvar commented
This is ready for another round of review when you are back :)

2022-10-17 11:20 UTC, maelle commented
Thank you!!

2022-10-17 11:20 UTC, merged